"use client"
import localFont from "next/font/local";
// import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '../../public/css/style.css'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

import ProviderWrapper from "./ProviderWrapper";
import { GoogleOAuthProvider } from "@react-oauth/google/dist";
import { useEffect } from "react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Dr Outlier Radiology",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const GOOGLE_CLIENT_ID = '459812214714-easrf4ejhh45a86fmnh6856qpok26022.apps.googleusercontent.com'
  const GOOGLE_CLIENT_ID = '90424675581-0d8lrekuq379coa2fpb9vhudttvs6k09.apps.googleusercontent.com'

  useEffect(() => {
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        navigator.serviceWorker.register('/service-worker.js')
          .then(registration => console.log('Service Worker registered:', registration))
          .catch(error => console.log('Service Worker registration failed:', error));
      });
    }
  }, []);

  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/public/images/login-logo.svg" />
        <title>Dr Outlier Radiology</title>
        <script src="/js/js.js"></script>
      </head>
      <body style={{ overflow: 'auto' }}>
        <div id="root">
          <ProviderWrapper>
            <GoogleOAuthProvider clientId={GOOGLE_CLIENT_ID}>
              {children}
            </GoogleOAuthProvider>
          </ProviderWrapper>
        </div>
        {/* {children} */}
      </body>
    </html>
  );
}
